name: projectkhadija
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.4.0
  flutter_paypal: ^0.2.1
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  flutter_local_notifications: ^19.2.1
  google_maps_utils: ^2.0.0+1
  geodesy: ^0.10.2

  # ✅ AJOUTÉS POUR LA FONCTION GPS + MAP
  geolocator: ^14.0.1
  google_maps_flutter: ^2.6.0

  # ✅ POUR FIREBASE
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.8
  firebase_database: ^11.3.6
  google_sign_in: ^6.3.0

  # Autres utiles
  provider: ^6.1.5
  flutter_foreground_task: ^9.1.0
  flutter_stripe: ^11.5.0
  supabase_flutter: ^2.9.0
  path: ^1.9.1
  file_picker: ^10.1.9
  mime: ^2.0.0
  uuid: ^4.5.1
  intl: ^0.20.2
  firebase_messaging: ^15.2.7
  permission_handler: ^12.0.0+1
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - images/khadija.jpg
    - images/