// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// choisi automatiquement les bonnes options selon la plateforme (web, android...).
class DefaultFirebaseOptions {
 // retourne les FirebaseOptions selon la plateforme.
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
//Configuration
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_hQctCJsRZH7CheIXEwz-1n8M3gylqpA',
    appId: '1:172697905456:web:30ba355fbd2f78faa240f5',
    messagingSenderId: '172697905456',
    projectId: 'crartenatm',
    authDomain: 'crartenatm.firebaseapp.com',
    storageBucket: 'crartenatm.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDr6VA9PWGhL65X5KP3KYPNhzcVkAWQN0',
    appId: '1:172697905456:android:a290f48a6cfb3dafa240f5',
    messagingSenderId: '172697905456',
    projectId: 'crartenatm',
    storageBucket: 'crartenatm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhgP9zq__wXUd7xC5U7Z06VOknJg7pr1Q',
    appId: '1:172697905456:ios:bbfbfb302139071ca240f5',
    messagingSenderId: '172697905456',
    projectId: 'crartenatm',
    storageBucket: 'crartenatm.firebasestorage.app',
    iosBundleId: 'com.example.projectkhadija',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhgP9zq__wXUd7xC5U7Z06VOknJg7pr1Q',
    appId: '1:172697905456:ios:bbfbfb302139071ca240f5',
    messagingSenderId: '172697905456',
    projectId: 'crartenatm',
    storageBucket: 'crartenatm.firebasestorage.app',
    iosBundleId: 'com.example.projectkhadija',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_hQctCJsRZH7CheIXEwz-1n8M3gylqpA',
    appId: '1:172697905456:web:4fbcf174ec8277e5a240f5',
    messagingSenderId: '172697905456',
    projectId: 'crartenatm',
    authDomain: 'crartenatm.firebaseapp.com',
    storageBucket: 'crartenatm.firebasestorage.app',
  );
}
